### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by potatoqualitee** [JustinGrote/PowerConfig#3]
Could this encompass some logging? I've noticed a lot of .NET projects support log4net.

**Comment by JustinGrote** [comment]
@potatoqualitee I've considered a separate project to configure the Microsoft.Extensions.Logging provider as a powershell module, which follows a similar model and allows for multiple provider backends like serilog, log4net, etc. 

It would be out of the scope of this module however, which is focused purely on providing a configuration provider for scripts/modules/etc.

There are a lot of logging frameworks already for PowerShell though so it's low on my priorities.

https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line
